---
# tasks file for createuser

- name: "Installattion apache/php"
  yum:
   name: "{{item}}"
   state: present
  loop:
   "{{apache_php}}"

- name: "droits sur html directory"
  file:
   path: /var/www/html
   state: directory
   mode: '0755'

- name: "supp index principal"
  file:
   path: /var/www/html/index.html
   state: absent

- name: "upload fichiers php"
  copy:
   src: files/
   dest: /var/www/html/

- name: "Resdemarrage php server"
  service:
     name: httpd
     state: restarted
     enabled: yes

- name: "default zone https service"
  firewalld:
   service: http
   permanent: yes
   state: enabled

- name: "restart systemd nginx service"
  systemd:
   name: firewalld
   enabled: yes
   state: restarted
